spring:
  application:
    name: rvcom
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.DB_URL }}
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

kakao:
  apikey: { { secrets.KAKAOMAP_API }